-- Ejecutar en Snowflake como ACCOUNTADMIN
-- Grants para que el usuario FORECAST_APP acceda a OFERTAS_DB

USE ROLE ACCOUNTADMIN;

GRANT USAGE ON WAREHOUSE OFERTAS_WH TO ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE OFERTAS_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA OFERTAS_DB.APP TO ROLE ACCOUNTADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA OFERTAS_DB.APP TO ROLE ACCOUNTADMIN;

-- El usuario FORECAST_APP necesita poder operar en OFERTAS_DB
GRANT USAGE ON WAREHOUSE OFERTAS_WH TO USER FORECAST_APP;
GRANT USAGE ON DATABASE OFERTAS_DB TO USER FORECAST_APP;
GRANT USAGE ON SCHEMA OFERTAS_DB.APP TO USER FORECAST_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA OFERTAS_DB.APP TO USER FORECAST_APP;
