-- ============================================================
-- App Ofertas v2 — NUEVAS TABLAS (KTM integrado)
-- Ejecutar en Snowflake como ACCOUNTADMIN
-- ============================================================

USE DATABASE OFERTAS_DB;
USE SCHEMA APP;

-- 1. TARIFAS: precios €/m³ por familia, artículo, densidad y planta
CREATE TABLE IF NOT EXISTS TARIFAS (
    ID              NUMBER AUTOINCREMENT PRIMARY KEY,
    FAMILIA         VARCHAR(100) NOT NULL,     -- BLOQUES.EPS, PANEL_AISLANTE.EPS, etc.
    ARTICULO        VARCHAR(150) NOT NULL,     -- EPS S, EPS 30 D10, KNAUF THERM TH 39, etc.
    MATERIA_PRIMA   VARCHAR(50) NOT NULL,      -- EPS_Blanco, EPS_Grafito, EPS_SOSTENIBLES
    DENSIDAD        NUMBER(5,1) NOT NULL,      -- 10, 12, 15, 20, 25, 30, 35
    LAMBDA          FLOAT,                     -- Conductividad térmica (opcional)
    PRECIO_VILAFRANCA  FLOAT DEFAULT 0,
    PRECIO_VALENCIA    FLOAT DEFAULT 0,
    PRECIO_VALLADOLID  FLOAT DEFAULT 0,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 2. CLIENTES: base de datos de clientes comerciales
CREATE TABLE IF NOT EXISTS CLIENTES (
    ID              NUMBER AUTOINCREMENT PRIMARY KEY,
    EMPRESA         VARCHAR(200) NOT NULL,
    CIF             VARCHAR(20),
    CONTACTO_NOMBRE VARCHAR(100),
    CONTACTO_APELLIDO VARCHAR(100),
    EMAIL           VARCHAR(200),
    TELEFONO        VARCHAR(50),
    MOVIL           VARCHAR(50),
    DIRECCION       VARCHAR(300),
    CP_CIUDAD       VARCHAR(150),
    COMERCIAL_ASIGNADO VARCHAR(100),
    MERCADO         VARCHAR(50),
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 3. TRANSPORTE: costes por planta
CREATE TABLE IF NOT EXISTS TRANSPORTE (
    ID              NUMBER AUTOINCREMENT PRIMARY KEY,
    PLANTA          VARCHAR(50) NOT NULL,
    COSTE_M3        FLOAT DEFAULT 0,
    COSTE_GRUPAJE_M3 FLOAT DEFAULT 0,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 4. MATERIAS_PRIMAS: precios base por kg de cada tipo EPS
CREATE TABLE IF NOT EXISTS MATERIAS_PRIMAS (
    ID              NUMBER AUTOINCREMENT PRIMARY KEY,
    TIPO            VARCHAR(50) NOT NULL UNIQUE,
    PRECIO_BASE_KG  FLOAT DEFAULT 0,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Seed materias primas
INSERT INTO MATERIAS_PRIMAS (TIPO, PRECIO_BASE_KG) VALUES ('EPS_Blanco', 1.45);
INSERT INTO MATERIAS_PRIMAS (TIPO, PRECIO_BASE_KG) VALUES ('EPS_Grafito', 1.75);
INSERT INTO MATERIAS_PRIMAS (TIPO, PRECIO_BASE_KG) VALUES ('EPS_SOSTENIBLES', 3.00);

-- Seed transporte (puedes ajustar)
INSERT INTO TRANSPORTE (PLANTA, COSTE_M3, COSTE_GRUPAJE_M3) VALUES ('Vilafranca', 3.44, 6.43);
INSERT INTO TRANSPORTE (PLANTA, COSTE_M3, COSTE_GRUPAJE_M3) VALUES ('Valencia', 3.65, 4.05);
INSERT INTO TRANSPORTE (PLANTA, COSTE_M3, COSTE_GRUPAJE_M3) VALUES ('Valladolid', 5.31, 5.46);

-- Actualizar PLANTAS con las 3 fábricas reales
TRUNCATE TABLE PLANTAS;
INSERT INTO PLANTAS (PLANTA, LARGO_MAX, ANCHO_MAX, GRUESO_MAX, MIN_M3) VALUES ('Vilafranca', 6110, 1215, 1050, 0.5);
INSERT INTO PLANTAS (PLANTA, LARGO_MAX, ANCHO_MAX, GRUESO_MAX, MIN_M3) VALUES ('Valencia', 4040, 1220, 1030, 0.5);
INSERT INTO PLANTAS (PLANTA, LARGO_MAX, ANCHO_MAX, GRUESO_MAX, MIN_M3) VALUES ('Valladolid', 4040, 1220, 1030, 0.5);

-- Grants
GRANT SELECT, INSERT, UPDATE, DELETE ON TARIFAS TO USER FORECAST_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON CLIENTES TO USER FORECAST_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON TRANSPORTE TO USER FORECAST_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON MATERIAS_PRIMAS TO USER FORECAST_APP;
